services:
  - type: web
    name: shrinkwrap
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GOOGLE_AI_API_KEY
        sync: false
      - key: EMAIL_SERVER_HOST
        sync: false
      - key: EMAIL_SERVER_PORT
        sync: false
      - key: EMAIL_SERVER_USER
        sync: false
      - key: EMAIL_SERVER_PASSWORD
        sync: false
      - key: EMAIL_FROM
        sync: false 